[package]
name = "monkey"
version = "1.0.0"
edition = "2021"
description = "A Monkey programming language interpreter written in Rust."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
